# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  # valid drivers options include "gd" or "gmagick" or "imagick"
  driver: "gd"
  filter_sets:
    carre: #nom du filtre
      quality: 75 #la qualité de l'image
      filters:
        thumbnail:
          size: [200, 200] #
          mode: outbound
    rectangle: #nom du filtre
      quality: 75 #la qualité de l'image
      filters:
        thumbnail:
          size: [250, 350] # height and then width
          mode: outbound
    echelle:
      quality: 85
      filters:
        scale: # ce filtre permet de reduire ou agrandir l'image quand c'est necessaire
          dim: [250, 250]
